spring.application.name=MiniDrive

# Server
server.port=8080

# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/minidrive_db
spring.datasource.username=root
spring.datasource.password=12345

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS S3
aws.s3.bucket-name=minidrive-divya
aws.region=ap-south-1
aws.access-key=YOUR_AWS_ACCESS_KEY
aws.secret-key=YOUR_AWS_SECRET_KEY

# File Size Limit
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

